FROM python:3.9-slim
RUN mkdir /code
# set current env
ENV HOME /code
WORKDIR /code
ENV PATH="/code/.local/bin:${PATH}"

#arg
ARG ENT_USERNAME
ARG ENT_PASSWORD
ARG COMMAND_EXECUTOR
ARG RESOURCE_URL
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
#env
ENV ENT_USERNAME $ENT_USERNAME
ENV ENT_PASSWORD $ENT_PASSWORD
ENV COMMAND_EXECUTOR $COMMAND_EXECUTOR
ENV RESOURCE_URL $RESOURCE_URL
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

RUN apt-get update && apt-get install -y git
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ADD . /code/
CMD ["python", "/code/main.py"]
